[dependencies]
deadpool-postgres = "0.10.5"
dotenv = "0.15.0"
once_cell = "1.17.1"
parking_lot = "0.12.1"
postgres-types = { features = ["derive"], version = "0.2.5" }
serde = { default-features = false, features = ["derive"], version = "1.0.163" }
serde_json = "1.0.96"
thiserror = "1.0.40"
time = { default-features = false, features = ["parsing", "serde"], version = "0.3.21" }
tokio-postgres = { default-features = false, features = ["with-serde_json-1", "with-time-0_3"], version = "0.7.8" }
twilight-model = "0.15.2"

[package]
edition = "2021"
name = "sakura-rs"
version = "0.1.0"